import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {Theme} from "@radix-ui/themes";
import AmiGoMainComponent from "../../components/main/AmiGoMainComponent";
import '@radix-ui/themes/styles.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
      <Theme appearance="dark" accentColor="red" panelBackground="solid" radius="large" scaling="95%">
      {children}
      </Theme>
      </body>
    </html>
  )
}
